site:
  about:
    siteName: Kodiak
    siteDescription: Wrappers around code documentation CLI tools to produce JSON models, usable as libraries

theme:
  social:
    other:
      - link: 'https://copper-leaf.github.io/kodiak'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/copper-leaf/kodiak'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'wikiSections'
    - type: 'page'
      itemId: 'Changelog'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    blue: '#48BAEF'
  palette:
    primary: 'BLUE'
    link: 'BLUE'

services:
  publications:
    stages:
      - type: githubPages
        repo: 'copper-leaf/kodiak'
        username: 'cjbrooks12'
      - type: githubReleases
        repo: 'copper-leaf/kodiak'

wiki:
  wikiPages:
    layout: wiki
    menu:
      - type: wiki

allPages:
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy
