
site:
  about:
    siteName: JSON Documentation Formatters
    siteDescription: A collection wrappers around various code documentation tools which produces a common JSON output readable by Orchid.

theme:
  social:
    other:
      - link: 'https://copper-leaf.github.io/dokka-json'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/copper-leaf/dokka-json'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'pages'
      group: 'languages'
    - type: 'page'
      itemId: 'Changelog'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    purple: '#48BAEF'
    blue: '#48BAEF'
  useSidebarSearch: true

services:
  publications:
    stages:
      - type: ghPages
        repo: 'copper-leaf/dokka-json'
        username: 'cjbrooks12'
      - type: githubReleases
        repo: 'copper-leaf/dokka-json'

allPages:
  components:
    - type: pageContent
    - type: prism
      githubTheme: 'duotone-light'
      languages:
        - 'groovy'
        - 'java'
        - 'kotlin'
      extraCss:
        - 'inline:all.scss:
          code.language-kotlin .token.number { margin: 0; padding: 0; background: none; border: none; font-size: 1em; min-width: 0; }
          code.language-kotlin .token.operator { margin: 0; padding: 0; background: none; border: none; font-size: 1em; min-width: 0; }
          '